# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-17 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_id',
            field=models.CharField(default='', max_length=255, verbose_name='User ID'),
            preserve_default=False,
        ),
    ]
